### ISSUE TITLE
Date format is broken work on ruby 1.8

### ISSUE THREAD

**Issue by iainbeeston** [ruby-json-schema/json-schema#198]
With draft4 schemas we validate dates using ruby's `DateTime.rfc3339` method. Unfortunately that doesn't exist before ruby 1.9, and on travis the ruby 1.8.7 build has lots of errors like this:

```
JSONSchemaDraft4Test#test_format_union:
NoMethodError: undefined method `rfc3339' for DateTime:Class
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/attributes/formats/date_time_v4.rb:8:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/attributes/format.rb:10:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:24:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:22:in `each'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:22:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema.rb:34:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/attributes/properties.rb:32:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/attributes/properties.rb:14:in `each'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/attributes/properties.rb:14:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:24:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:22:in `each'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema/validator.rb:22:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/schema.rb:34:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/validator.rb:110:in `validate'
    /home/travis/build/ruby-json-schema/json-schema/lib/json-schema/validator.rb:275:in `fully_validate'
    /home/travis/build/ruby-json-schema/json-schema/test/test_helper.rb:33:in `refute_valid'
    /home/travis/build/ruby-json-schema/json-schema/test/support/string_validation.rb:75:in `test_format_union'
```
